<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Il nome utente non può essere modificato.' => '',
  'Il ruolo Admin avrà accesso sia alla gestione dati statistici sia alla gestione utenti.' => '',
  'Inserire il nome utente che sarà utilizzato per autenticarsi.' => '',
  'Inserire la password che sarà utilizzata per autenticarsi.' => '',
  'Inserire un nome identificativo per questo utente.' => '',
  'Inserire una nuova password o lasciare il campo vuoto per non modificare la password.' => '',
);
