<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Allow' => '',
  'Create' => '',
  'Create new role' => '',
  'Delete' => '',
  'ID' => '',
  'Main search' => '',
  'Name' => '',
  'Password' => '',
  'Permissions successfully saved, please set permissions.' => '',
  'Permissions successfully saved.' => '',
  'Please fill out the following form with your login credentials:' => '',
  'Read' => '',
  'Role' => '',
  'Search' => '',
  'Tstamp' => '',
  'Unable to delete selected role' => '',
  'Update' => '',
  'Update role' => '',
  'Username' => '',
  'Users administration' => '',
  'User|Users' => '',
  'View' => '',
  'View role {role}' => '',
  'Welcome to {appname}' => '',
  'No' => 'No',
  'Unable to delete selected user' => 'Unable to delete selected user',
  'User has been created.' => 'User has been created.',
  'Yes' => 'Yes',
);
