<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Insert a new password or leave empty for no change' => '',
  'My Date' => '',
  'My Time' => '',
  'Reset' => '',
  'Role for \'administrator\' cannot be changed.' => '',
  'Role name cannot be changed' => '',
  'Select one or more roles for this user.' => '',
  'Set permissions for this role.' => '',
  'Submit' => '',
  'The login name for this user' => '',
  'The login password for this user' => '',
  'The name for this role' => '',
  'The name for this user' => '',
  'Type or select roles for this user.' => '',
  'Username cannot be changed' => '',
);
