<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Auth check' => '',
  'Calendar' => '',
  'Create role' => '',
  'Create user' => '',
  'Cron' => '',
  'Date and time' => '',
  'Drag & drop' => '',
  'Elements' => '',
  'Examples' => '',
  'Excel download' => '',
  'Manage roles' => '',
  'Manage users' => '',
  'Menu' => '',
  'Messages' => '',
  'Node JS' => '',
  'Option 1' => '',
  'Option 2' => '',
  'Option 3' => '',
  'Option 4' => '',
  'PDF download' => '',
  'Simple link' => '',
  'Login' => 'Login',
  'Logout' => 'Logout',
  'Users' => 'Users',
);
