filter:
    excluded_paths:
        - 'vendor/*'
tools:
    php_cpd:
        filter:
            excluded_paths: ['vendor/*', 'app/*', 'web/*']
    php_pdepend: true
    php_mess_detector:
        filter:
            excluded_paths: ['vendor/*', 'app/*', 'web/*']
    php_loc: true
    external_code_coverage:
        timeout: '600'
        filter:
            excluded_paths: ['vendor/*']